# ======================================================================
# Makefile
# ======================================================================

EXE = ch3-assert-retract
SOURCES = ch3-assert-retract.pl show_list.pl basic_data.pl rules.pl

include ../mk/common.mk
