# ======================================================================
# Makefile
# ======================================================================

EXE = ch2-main-variations
SOURCES = showargs.pl ch2-main-variations.pl 

include ../mk/common.mk
