# ======================================================================
# Makefile
# ======================================================================

EXE = ch3-assert-retract
SOURCES = ch3-assert-retract.pl  show_list.pl  tools.pl

include ../mk/common.mk
